source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.0"

gem "rails", "~> 6.1.0"
gem "pg"
gem "puma"
gem "bootsnap", require: false
gem "olive_branch"
gem "rack-cors"
gem "ranked-model"

group :development, :test do
  gem "pry-rails"
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem "listen"
  gem "spring"
end
